FROM golang:1.22

WORKDIR /app

# Install air for hot reload
RUN go install github.com/air-verse/air@v1.52.2
# Install swag CLI
RUN go install github.com/swaggo/swag/cmd/swag@latest

# Install development dependencies
RUN apt-get update && apt-get install -y \
    postgresql-client \
    redis-tools \
    && rm -rf /var/lib/apt/lists/*

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN make swagger

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]